name: DevSecOps CI/CD

on:
  push:
    branches: [ '*' ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scans:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Secret scanning (Gitleaks) ---
      - name: Varredura de segredos (Gitleaks)
        uses: gitleaks/gitleaks-action@v1.6.0