# .github/workflows/semgrep-csharp.yml
name: Semgrep (C#) — Community

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  semgrep_scan:
    name: semgrep/ci
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read
      actions: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep (C# + Secrets)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            --workdir /src \
            semgrep/semgrep:latest \
            semgrep scan \
              --config "p/auto" \
              --sarif --output semgrep-results.sarif
        continue-on-error: true

      - name: Upload SARIF to Advanced Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep-csharp
        if: always()
